### ISSUE TITLE
[Bug] hue2mqtt always post to "undefined" topic

### ISSUE THREAD

**Issue by dannykorpan** [mqtt-home/hue-to-mqtt-gw#649]
Hi,

thanks for your work and this project! 🙏

I've using hue2mqtt via a docker-compose.yml. This is my docker-compose.yml:
```
...
  huemqtt:
    container_name: hue2mqtt
    hostname: huemqtt
    image: pharndt/hue2mqtt:2.11.4
    volumes:
      - ./hue2mqtt:/var/lib/huemqtt:ro
    restart: always
 ...
```

and this is my config.json
```
{
    "mqtt": {
        "url": "tcp://ip-of-my-mosquitto-server:1883"
    },
    "hue": {
        "host": "ip-of-my-hue-bridge",
        "api-key": "api-key-of-my-hue-bridge-app",
    }
}
```

The communication between hue2mqtt and mosquitto is working instantly, but the topic which is hue2mqtt posting to mosquitto is always "undefined".

<img width="628" alt="grafik" src="https://github.com/mqtt-home/hue-to-mqtt-gw/assets/8004507/2330003b-3c99-40d7-b59f-32e4e69d6d54">

Where do I set the topic?

Thanks for your help in advance,
Danny
